[package]
name = "ray-tracing"
version = "0.1.0"
authors = ["Richard Thomas <richard.thomas@interfront.co.za>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
